version: "1"
run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - gocritic
    - nestif
    - prealloc
    - unparam
    - goconst
  disable:
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 10
  misspell:
    locale: DE
  nestif:
    min-complexity: 4
